#!/bin/env python
"""Tidy: a document management system.
usage: tid [--version] [--debug] [--tidy-dir=<path>] [--help]
           <command> [<args>...]

Options:
    -d, --debug           Show debugging info.
    -h, --help            Show this screen.
    -v, --version         Show version.

Commonly used tid commands in various situations:

start a new collection:
    init      Create an empty collection or rebuild an existing one.
    demo      Create a demo collection with some data in it.

work on collections:
    import    Add file contents or pipe stdout into Tidy.
    clone     Add file contents and keep the directory structure intact.
    mkdir     Create the group(s), if they do not exist already.
    mv        Move or rename an entry, a group, or a collection.
    rm        Remove entries / groups from the collection.

manage tags:
    tag       Add tags to an entry / group / collection.

virtual mounting:
    mount     Mount a collection / group as a virtual filesystem.
    commit    Apply changes made to the virtual filesystem to the collection.
    umount    Unmount virtual filesystems.

retrieve what you want:
    ls        List information about the collections / groups / entries.
    search    Search the database.
    open      Open a file with xdg-open.
    locate    Show the actual location of a file in the file system.

backup and sync:
    backup    Make backups.

AI functions:
    train     Train the AI models using your own data.
    ai        Invoke AI functionalities.

configurations:
    config    Inspect or modify configs.
"""

__copyright__ = "Copyright (C) 2018 Xiaoyu Wei"

__license__ = """
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from docopt import docopt
from subprocess import call
from tidy import version

import logging
logger = logging.getLogger("TIDY")

def log_dict(dictionary, indent=0):
    """Logging dictionary with indent.
    """
    prefix = ''.join('\t' for i in range(indent))
    return prefix + prefix.join(
            dictionary.__repr__().splitlines(True)
            )

def parse_command_args(doc, command, args):
    """Process Tidy commands with docopt.
    """
    logger.debug("Entering Tidy command: " + command)
    command_args = docopt(doc, argv=[command] + args)
    logger.debug("Running init command with arguments:\n" +
            log_dict(command_args, 1))
    return command_args

if __name__ == '__main__':

    # Parse command line input
    arguments = docopt(__doc__,
                       version="\n".join(
                           ["tid (Tidy) " + version.VERSION_TEXT + "\n",
                               __copyright__,
                               __license__,
                               ]),
                       options_first=True)

    # Set logging level
    if arguments['--debug']:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    logger.info("This is Tidy, version " + version.VERSION_TEXT)
    logger.debug("Received global arguments:\n" + log_dict(arguments, 1))

    # Read configs
    from tidy.config import config_handler

    # Execute command
    command = arguments['<command>']
    if command == 'init':
        from tidy.cli.commands import collection_init
        cargs = parse_command_args(collection_init.__doc__,
                command, arguments['<args>'])

    elif command == 'demo':
        raise NotImplementedError("Demo is not available yet")

    else:
        raise NotImplementedError("Unknown command: " + command)

# vim: ft=python
