#!/bin/env python
"""Tidy: a document management system.
usage: tid [--version] [--tidy-dir=<path>] [--help]
           <command> [<args>...]

Options:
    -h, --help            Show this screen.
    -v, --version         Show version.

Commonly used tid commands in various situations:

start a new collection:
    init      Create an empty collection or rebuild an existing one.
    demo      Create a demo collection with some data in it.

work on collections:
    import    Add file contents or pipe stdout into Tidy.
    clone     Add file contents and keep the directory structure intact.
    mkdir     Create the group(s), if they do not exist already.
    mv        Move or rename an entry, a group, or a collection.
    rm        Remove entries / groups from the collection.

manage tags:
    tag       Add tags to an entry / group / collection.

virtual mounting:
    mount     Mount a collection / group as a virtual filesystem.
    commit    Apply changes made to the virtual filesystem to the collection.
    umount    Unmount virtual filesystems.

retrieve what you want:
    ls        List information about the collections / groups / entries.
    search    Search the database.
    open      Open a file with xdg-open.
    locate    Show the actual location of a file in the file system.

backup and sync:
    backup    Make backups.

AI functions:
    train     Train the AI models using your own data.
    ai        Invoke AI functionalities.

configurations:
    config    Inspect or modify configs.
"""

__copyright__ = "Copyright (C) 2018 Xiaoyu Wei"

__license__ = """
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from docopt import docopt
from subprocess import call
import tidy.version as version

if __name__ == '__main__':

    arguments = docopt(__doc__,
                       version="\n".join(["tid (Tidy) " + version.VERSION_TEXT + "\n",
                                          __copyright__,
                                          __license__,
                                          ]),
                       options_first=True)
    print(arguments)
    print(arguments['<command>'])

    # refer to https://github.com/docopt/docopt/blob/master/examples/git/git.py

# vim: ft=python
